#include "afpRefreshIcon.h"

/*
 * afpRefreshIcon.cpp
 *
 * 16x16, 1-bit-per-pixel refresh (circular arrow) icon.
 *
 * The glyph is a clockwise circular arrow: a ring with a filled
 * triangular arrowhead in the upper right, the same shape as the
 * reload/refresh button in a web browser.  Bit = 1 is a pixel of the
 * icon; bit = 0 is transparent.  Row-major, MSB-first, top row first.
 */

const uint8_t kRefreshIconBitmap[
	kRefreshIconWidth * kRefreshIconHeight / 8
] = {
	0x00, 0x00,	// ................
	0x00, 0x00,	// ................
	0x03, 0x80,	// ......###.......
	0x0C, 0x40,	// ....##...#......
	0x18, 0x20,	// ...##.....#.....
	0x10, 0x1C,	// ...#.......###..
	0x20, 0x3C,	// ..#.......####..
	0x20, 0x6C,	// ..#......##.##..
	0x20, 0x04,	// ..#..........#..
	0x20, 0x00,	// ..#.............
	0x10, 0x08,	// ...#........#...
	0x18, 0x18,	// ...##......##...
	0x0C, 0x30,	// ....##....##....
	0x07, 0xE0,	// .....######.....
	0x00, 0x00,	// ................
	0x00, 0x00	// ................
};