build_mode: 1
build_file_path: ""
project_release_build_command: DBG= DBGR= make
project_release_clean_command: make clean
project_release_execute_args: ""
project_release_target: objects.x86_64-cc13-release/afp_server
project_debug_build_command: DBG="DEBUG" DBGR="TRUE" make
project_debug_clean_command: DBG="DEBUG" DBGR="TRUE" make clean
project_debug_execute_args: ""
project_debug_target: objects.x86_64-cc13-debug/afp_server
project_run_in_terminal: false